#!/bin/bash
# NotebookLM Auth Setup Script
# Run this on your LOCAL machine (Windows/Mac/Linux)
# Then upload the storage_state.json to your VPS

set -e

echo "=== NotebookLM Auth Setup ==="
echo ""
echo "1. Install notebooklm-py on your local machine:"
echo ""
echo "   Windows (PowerShell):"
echo "     pip install \"notebooklm-py[browser]\""
echo "     playwright install chromium"
echo ""
echo "   Mac/Linux:"
echo "     pip install \"notebooklm-py[browser]\""
echo "     playwright install chromium"
echo ""
echo "2. Login (opens browser):"
echo ""
echo "     notebooklm login"
echo ""
echo "   This opens Chromium. Sign in with war.peace.love@gmail.com"
echo "   Wait until you see 'Login successful' or similar."
echo ""
echo "3. Find the auth file:"
echo ""
echo "   Windows:  C:\\Users\\%USERNAME%\\.notebooklm\\profiles\\default\\storage_state.json"
echo "   Mac/Linux: ~/.notebooklm/profiles/default/storage_state.json"
echo ""
echo "4. Upload to VPS:"
echo ""
echo "   From Windows (PowerShell):"
echo "     scp \"$USERPROFILE\\.notebooklm\\profiles\\default\\storage_state.json\" ubuntu@YOUR_VPS_IP:~/.notebooklm/profiles/default/storage_state.json"
echo ""
echo "   From Mac/Linux:"
echo "     mkdir -p ~/.notebooklm/profiles/default"
echo "     scp ~/.notebooklm/profiles/default/storage_state.json ubuntu@YOUR_VPS_IP:~/.notebooklm/profiles/default/storage_state.json"
echo ""
echo "5. On VPS, verify it works:"
echo ""
echo "     notebooklm list"
echo ""
echo "6. Auto-refresh is set up via cron (runs daily at 3 AM)."
echo "   To refresh manually: notebooklm auth refresh"
echo ""
echo "=== Done ==="
